Upgrade Ruby version to 3.2.1
jenkinsci/docker-inbound-agents pull request #35
Opened 2023-03-13 10:34 UTC by pablogrs

Ruby version upgraded to 3.2.1
Java version upgraded to Java 11 using SDKMan

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-03-19 20:56 UTC, dduportal reviewed
Thanks for this contribution ? Would you be willing to update your PR to use the JDK embeded in the `jenkins/inbound-agent:alpine` image ?

The Jenkins project uses Temurin and that would be a great way to keep a constant behavior WDYT?

2023-03-20 12:35 UTC, pablogrs commented
> Thanks for this contribution ? Would you be willing to update your PR to use the JDK embeded in the `jenkins/inbound-agent:alpine` image ?
> 
> The Jenkins project uses Temurin and that would be a great way to keep a constant behavior WDYT?

Hi, of course, let me check if I understand first.
Instead of using [jenkins-inbound](https://github.com/jenkinsci/docker-inbound-agents/pull/35/files#diff-4b62900532c579e3c7c952ed7e68a5614cfb8f35adf4640c4523c54fd3e29271R1) as a source for Jenkins files you are asking to make it the base image, is that right?

2023-03-20 12:55 UTC, dduportal commented
> Hi, of course, let me check if I understand first. Instead of using [jenkins-inbound](https://github.com/jenkinsci/docker-inbound-agents/pull/35/files#diff-4b62900532c579e3c7c952ed7e68a5614cfb8f35adf4640c4523c54fd3e29271R1) as a source for Jenkins files you are asking to make it the base image, is that right?

Both "methods" are valid (each one as its pros and cons)

- Either using the `jenkins/inbound-agent` as base image,
- OR importing only the requirements using the current "multistage" pattern.

In order to avoid "big changes" , what do you think keeping the actual pattern, but copying the requirements from the `jnlp` stage?

You have an example here: https://github.com/jenkins-infra/docker-packaging/blob/7c8ac52f2bfe510d5431ccc7169aa3233700bec2/Dockerfile#L93-L95

2023-03-22 13:50 UTC, dduportal requested changes
That is an excellent work!

I've added one last mandatory suggestion to use a Debian based Inbound Agent to ensure that the JDK used is prepared for Debian glibc (as the previous Alpine would have a JDK installation for musl which will probably not work).


Once added, the PR is ready to go!

2023-03-22 13:50 UTC, dduportal commented on ruby/Dockerfile
> +FROM jenkins/inbound-agent:alpine as jenkins-agent
```suggestion
# jdk11 is a Debian based image
FROM jenkins/inbound-agent:jdk11 as jenkins-agent
```

2023-03-22 14:32 UTC, pablogrs commented on ruby/Dockerfile
> +FROM jenkins/inbound-agent:alpine as jenkins-agent
Thanks for that, I didn't realise, yes it would make it fail!

2023-03-22 14:33 UTC, dduportal approved these changes
LGTM, many thanks!

2023-03-27 07:16 UTC, merged